// Generates Studio bundles; source example.luau retains its loadstring loader.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const root = new URL('./', import.meta.url);
const library = readFileSync(new URL('Serotonin.luau', root), 'utf8');
const demo = readFileSync(new URL('Demo.client.luau', root), 'utf8').replace(/^local Serotonin = require\([^\n]+\)\r?\n/m, '');
const output = new URL('SerotoninDemo.client.luau', root);
const bundled = '-- Generated by node roblox-ui/build.mjs. Paste into a client LocalScript.\nlocal Serotonin = (function()\n' + library + '\nend)()\n\n' + demo;
writeFileSync(output, bundled);
const source = bundled.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
writeFileSync(new URL('SerotoninDemo.rbxmx', root), `<?xml version="1.0" encoding="utf-8"?>\n<roblox version="4"><Item class="LocalScript" referent="RBX0"><Properties><string name="Name">SerotoninDemo</string><bool name="Disabled">false</bool><ProtectedString name="Source">${source}</ProtectedString></Properties></Item></roblox>\n`);
console.log(fileURLToPath(output));
const example = readFileSync(new URL('example.luau', root), 'utf8');
const exampleBody = example.replace(/-- BEGIN LIBRARY LOADER[\s\S]*?-- END LIBRARY LOADER/, 'local UI = Serotonin');
if (exampleBody === example) throw new Error('example.luau is missing its loader markers');
writeFileSync(new URL('Example.client.luau', root), '-- Generated Studio-compatible version of example.luau.\nlocal Serotonin = (function()\n' + library + '\nend)()\n\n' + exampleBody);
